name: Learn basic of GitHub Action
on:
  push:
    branches:
      -  master
jobs:
  install-java:
    runs-on: ubuntu-latest
   
    container:
      image: alpine:latest
    steps:
      - name: install java
        run: apk add --no-cache openjdk11-jdk
      - name: print java -version
        run: java --version
